Deepak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from deepakblog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrcrm.urls')),
    path('', include('deepakblog.urls')),
    
    # path('musicianDelete/<int:id>/', views.musicianDelete),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

deepakblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'deepakblog'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.homeview, name='home'),
    path('userlogin/', views.userlogin, name='userlogin'),
    path('userlogout/', views.userLogout, name='userlogout'),
    path('musicianDelete/', views.musicianDelete, name="musicianDelete"),
    path('productMaster/', views.productMaster, name="productMaster"),
    path('productMasterView/', views.productDetailsMaster, name="productMasterView"),
    path('productMasterShow/', views.productDetailsMasterShow, name="productMasterShow"),
    path('bookMaster/', views.bookMasterDetails, name="bookMaster"),
    path('testMail/', views.sendTestMail, name="testMail"),
    path('paymentBook/', views.payofbookprice, name="paymentBook"),
]

hrcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'hrcrm'
urlpatterns = [
    path('hrcrm/', views.index, name = 'index'),
    
]

deepakblog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Post(models.Model):
    content = RichTextField()
# Create your models here.
class Musician(models.Model):
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    instrument = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return self.first_name

class productType(models.Model):
    id = models.AutoField(primary_key=True)
    productType = models.CharField('Product Type', max_length=30)
    def __str__(self):
        return self.productType
class productCategories(models.Model):
    id = models.AutoField(primary_key=True)
    productType = models.ForeignKey(productType, on_delete=models.CASCADE)
    productcategorie = models.CharField('Product Categories', max_length=30)
    def __str__(self):
        return self.productcategorie 
class productMaster(models.Model):
    active = (
        ('1','Active'),
        ('0', 'Inactive')
    )
    id = models.AutoField(primary_key=True)
    productName = models.CharField('Product Name', max_length = 50)
    productType = models.ForeignKey(productType, on_delete=models.CASCADE)
    productCategories = models.ForeignKey(productCategories, on_delete=models.CASCADE)
    productPrize = models.IntegerField()
    productReleaseDate = models.DateField(max_length = 50)
    productProductImage = models.ImageField(null=True,blank=True, upload_to='uploads/')
    productDescription = RichTextUploadingField()
    active = models.CharField('Active', max_length=10, choices=active, blank=True)

class bookMaster(models.Model):
    id = models.AutoField(primary_key=True)
    bookName = models.CharField('Book Name', max_length = 50)
    bookImage = models.ImageField('Upload Image', null=True,blank=True, upload_to='uploads/')
    bookDescription = RichTextUploadingField('Book Description') 
    price = models.IntegerField('Price Of The Book', default='20')   

deepakblog/forms.py
from django.core import validators
from django import forms
from .models import Musician, productMaster, bookMaster
# from django.core.files.uploadedfile import SimpleUploadedFile
from ckeditor.widgets import CKEditorWidget

# ####model froms data define
class MusicianForm(forms.ModelForm):
    class Meta:
        model = Musician
        fields = ['first_name', 'last_name', 'instrument']
        widgets = {
           'first_name':forms.TextInput(attrs={'class':'form-control'}),
           'last_name':forms.TextInput(attrs={'class':'form-control'}),
           'instrument':forms.TextInput(attrs={'class':'form-control'}), 
        }
class productMasterForm(forms.ModelForm):
    class Meta:
        model = productMaster
        fields = '__all__'
        widgets = {
           'productName':forms.TextInput(attrs={'class':'form-control'}),
           'productType':forms.Select(attrs={'class':'form-control'}),
           'productCategories':forms.Select(attrs={'class':'form-control'}),
           'productPrize':forms.TextInput(attrs={'class':'form-control'}),
           'productReleaseDate':forms.DateInput(attrs={'class':'form-control'}),
        #    'productProductImage':forms.CharField(widget=CKEditorWidget()), 
           'productDescription':forms.CharField(widget=CKEditorWidget()),
           'active':forms.Select(attrs={'class':'form-control'}), 
        } 
#  Book Master Details
class bookMasterForms(forms.ModelForm):
    class Meta:
        model = bookMaster
        fields = '__all__'
        widgets = {
           'bookName':forms.TextInput(attrs={'class':'form-control'}),
           'bookDescription':forms.CharField(widget=CKEditorWidget()),
        }

    

deepakblog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.core.serializers import serialize
from deepakblog.forms import *
from .models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail


# Create your views here.

def homeview(request):
    return render(request, 'deepakblog/home.html')       
def userlogin(request):
    if request.method == "POST":
        fm = AuthenticationForm(request = request, data = request.POST)
        if fm.is_valid():
            username = fm.cleaned_data['username']
            password = fm.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                # A backend authenticated the credentials
                login(request, user)
                messages.success(request, 'login sucessfully!!')
                return redirect('/')
            else:
                messages.info(request, 'User Name and password is incorrect')
    fm = AuthenticationForm()
    return render(request, 'deepakblog/login.html', {'form':fm})

    # Musician Details Add Edit
def userLogout(request):
        logout(request)
        return redirect('deepakblog:userlogin')
@login_required(login_url='deepakblog:userlogin')    
def index(request):
    if request.method =='POST' and request.POST.get('mid'):
        mId = request.POST.get('mid')
        Musiciandata = Musician.objects.get(pk=mId)
        serializedData = serialize('json', [ Musiciandata, ])
        return HttpResponse(serializedData)
    elif request.method =='POST':
        if request.POST.get('EditId'):
            EditId = request.POST.get('EditId')
            cmaster = Musician.objects.filter(pk=EditId).update(first_name = request.POST.get('first_name'), last_name = request.POST.get('last_name'), instrument = request.POST.get('instrument'))
            messages.success(request, 'Musician data updated sucessfully!!')
            return redirect('/')
        else:
            fm = MusicianForm(request.POST)
            if fm.is_valid():
                fn = fm.cleaned_data['first_name']
                fl = fm.cleaned_data['last_name']
                ins = fm.cleaned_data['instrument']
                reg = Musician(first_name = fn, last_name = fl, instrument = ins)
                messages.success(request, 'Musician data added sucessfully!!')
                reg.save()
                fm = MusicianForm()
    else:
        fm = MusicianForm()
    music = Musician.objects.all()
    current_user = request.user
    # print (current_user.id)
    return render(request, 'deepakblog/index.html', {'form': fm, 'music': music ,'name':request.user})
    
    # Delete Musician Records
@login_required(login_url='deepakblog:userlogin')
def musicianDelete(request):
    if request.method=='POST':
        musicID = request.POST.get('musicID')
        musicianDel = Musician.objects.filter(pk=musicID).delete()
        # print(musicianDel)
        messages.success(request, 'Musician data deleted sucessfully!!')
        return redirect('/')
# products Page

@login_required(login_url='deepakblog:userlogin')
def productMaster(request):
    return render(request, 'deepakblog/products.html')

@login_required(login_url='deepakblog:userlogin')
def productDetailsMaster(request):
    if request.method == 'POST':
        forms = productMasterForm(request.POST, request.FILES)
        if forms.is_valid():
            messages.success(request, 'Product saved sucessfully!!')
            forms.save()
            return redirect('deepakblog:productMasterShow')
    else:        
        forms = productMasterForm()
    # product = productMaster.objects.all()
    context = {'forms': forms}
    return render(request, 'deepakblog/productMasterDetails.html', context)

@login_required(login_url='deepakblog:userlogin')       
def productDetailsMasterShow(request):
    # product = productMaster.objects.get()
    return render(request, 'deepakblog/showproductData.html')

@login_required(login_url='deepakblog:userlogin')       
def bookMasterDetails(request):
    if request.method == 'POST':
        forms = bookMasterForms(request.POST, request.FILES)
        if forms.is_valid():
            messages.success(request, 'Book added sucessfully!!')
            forms.save()
    forms = bookMasterForms()
    book = bookMaster.objects.all()
    context = {'forms':forms, 'book':book}
    return render(request, 'deepakblog/bookData.html',context)

@login_required(login_url='deepakblog:userlogin')
def sendTestMail(request):
    send_mail(
    'Subject here',
    'Here is the message.',
    'dg285986@gmail.com.com',
    ['guptadm143@gmail.com'],
    fail_silently=False,
    )
    return HttpResponse("Email Send Successfully!!")


@login_required(login_url='deepakblog:userlogin')
def payofbookprice(request):
    return render(request, 'deepakblog/payment.html')
    

templates/deepakblog/bookData.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deepak ::.Product Master.::</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
    <style>
        *{
            margin: 0px;
            padding: 0px;
        }
        .col-md-6 label{
            padding-top: 15px;
            padding-bottom: 5px;
        }
    </style>
    {{ form.media }}
</head>
<body>
    {% include 'deepakblog/header.html' %}
    <div class="container-fluid">
        
            {% block content %}
                <h3 class="BookMaster text-white text-center">Book Master Whole Process</h3>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
                            <strong><li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li></strong>
                        </div>
                        {% endfor %}
                    </ul>
                {% endif %}
                <div class="container mx-5">
                    <div class="row">
                        <div class="col-md-10">
                            <form action="{% url 'deepakblog:bookMaster' %}" method="POST"  enctype="multipart/form-data">
                                {% csrf_token %}
                                {{forms.media }}
                                {{forms.as_p}} 
                                <input type="submit" class="btn btn-primary">
                            </form>
                        </div>
                    </div>
                </div>
                {% if book %}
                    {% for Book in book %}
                        <div class="container mx-5 col-md-6">
                            <h3 class="text-center text-danger py-3">{{Book.bookName}}</h3>
                            <img src="/media/{{Book.bookImage}}" alt="BookImages" class="mx-4 img-responsive imgfluid img-rounded" width="100%">
                            <p class="py-2 mx-4 text-center text-dark bordered-3">
                                {{Book.bookDescription}}
                            </p>
                            <div class="d-flex d-inline">
                                <a href="{% url 'deepakblog:paymentBook' %}" class="btn btn-danger">Buy Book</a> &nbsp;&nbsp;
                                <button class="btn btn-danger"> 20 <i class="fa fa-inr" aria-hidden="true"></i></button>
                            </div>
                        </div>
                    {% endfor%}
                {% endif %}
            {% endblock content %}
        
    </div>
    {% include 'deepakblog/footer.html' %}
    <!-- <script src="{% static 'js/bootstrap.js' %}"></script> -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- <script src="{% static 'js/all.min.js' %}"></script> -->
    <!-- <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script> -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    </body>
    </html>

templates/deepakblog/header.html
  {% load static %}
  <link rel="icon" href="{% static 'images/favicon-32x32.png' %}" type="image/ico" />
  <link rel="stylesheet" href="{% static 'icofont/icofont.min.css' %}">
  <link rel="stylesheet" href="{% static 'icofont/icofont.css' %}">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark sticky-top" style="height: 100px; background-color: #020031;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'deepakblog:home' %}"><i class="fas fa-crown"></i>Technology</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'deepakblog:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'hrcrm:index' %}">HR CRM</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown button
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'deepakblog:productMaster' %}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'deepakblog:bookMaster' %}">Book Master</a>
          </li>
        </ul>
          <span class="p-1 text-white">Hi, {{request.user}}</span>&nbsp;&nbsp;
          <a href="{% url 'deepakblog:userlogout' %}" class="btn btn-outline-danger" type="submit">Logout</a>
      </div>
    </div>
  </nav>

templates/deepakblog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deepak Blog</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    {% include 'deepakblog/header.html' %}
    {% block content %}
    <div class="conatiner m-2">
        <h4 class="text-success text-uppercase text-center">Welcome {{request.user}}, Crud Operation with Django</h4>
        <div class="d-flex justify-content-end">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Add Musician
            </button>
        </div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
                    <strong><li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li></strong>
                  </div>
                {% endfor %}
            </ul>
        {% endif %}
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Musician Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="" method="POST">                
                    <div class="modal-body">
                        <span id="musicianId"></span>
                        {% csrf_token %}
                        {{form.as_p}}
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-secondary">Save</button>
                        <button type="reset" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
        <div class="container-md py-2" >
            <h4 class="text-center">Musician Details</h4>
            <table class="table table-info table-striped table-responsive text-center">
                <thead>
                    <tr class="bg-dark">
                      <th>S.R</th>
                      <th>First Name</th>
                      <th>Last Name</th>
                      <th>Instrument</th>
                      <th>Edit</th>
                      <th>Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for musician in music %}
                        <tr>
                            <td>{{musician.id}}</td>
                            <td>{{musician.first_name}}</td>
                            <td>{{musician.last_name}}</td>
                            <td>{{musician.instrument}}</td>
                            <td>
                                <a href="#" class="btn btn-success" onclick="showMusician({{musician.id}})">Edit</a>
                            </td>
                            <td>
                                <form action="{% url 'deepakblog:musicianDelete' %}" method="POST">
                                    <input type="hidden" value="{{musician.id}}" name="musicID">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endblock content %}
    {% include 'deepakblog/footer.html' %}
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/all.min.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
    <script>
        function showMusician(id)
        {
            var mid = id;
            var token = '{{csrf_token}}';
            $('#musicianId').html('<input type="hidden" id="EidtId" name="EditId">');
            $.ajax({
                headers: { "X-CSRFToken": token },
                url: '',
                type: 'POST',
                data: {mid:mid},
                dataType: 'json',
                success: function (data) {
                    $('#EidtId').val(data[0].pk);
                    var data = data[0].fields;
                    $('#id_first_name').val(data.first_name);
                    $('#id_last_name').val(data.last_name);
                    $('#id_instrument').val(data.instrument);
                    $('#exampleModal').modal('show');
                }
            });
        }
    </script>
</body>
</html>

templates/deepakblog/products.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deepak Products</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        *{ 
            margin: 0;
            padding: 0;
        }
        .product-icon
        {
            height: 20px;
            width: 20px;
            background-color: rgb(8, 1, 107);
            border-radius: 50%;
            display: inline-block;
        }
        .icofont{
            color: #000;
        }
        .card{
            height: 250px;
        }
    </style>
</head>
<body>
    {% include 'deepakblog/header.html' %}
        {% block content %}
            <h3 class="text-center text-danger">All Our Products</h3>
            
            <div class="container-fluid text-white">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card bg-danger">
                                <div class="card-header">
                                <span class=""><i class="product-icon"></i></span>  Product Master
                                </div>
                                <div class="card-body">
                                  <a href="{% url 'deepakblog:productMasterView' %}"class="text-white nav-link"><i class="text-dark fa fa-check "></i> Add Product Details</a>
                                  <a href="{% url 'deepakblog:testMail' %}" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Show Product</a>
                                  <a href="{% url 'deepakblog:testMail' %}" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Product Management</a>
                                  <a href="{% url 'deepakblog:testMail' %}" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Product Categories Filter</a>
                                
                                </div>
                              </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-danger">
                                <div class="card-header">
                                    <span class=""><i class="product-icon"></i></span> Email Master
                                </div>
                                <div class="card-body">
                                  <a href="{% url 'deepakblog:testMail' %}" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Test Email</a>
                                  <a href="{% url 'deepakblog:testMail' %}" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Test Email With Attatchment</a>
                                  <a href="{% url 'deepakblog:testMail' %}" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Test Email Specific Attatchment</a>
                                  <a href="{% url 'deepakblog:testMail' %}" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Test Email send invoice to user</a>
                                
                                </div>
                              </div> 
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-danger">
                                <div class="card-header">
                                <span class=""><i class="product-icon"></i></span>Payment Gatewaye paypal 
                                </div>
                                <div class="card-body">
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Test payment </a>
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Configuration Documnets </a>
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Product Buy and Add to Cart </a>
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Security To Handle Payment Process Does Not Hacked</a>
                                </div>
                              </div>
                        </div>
                    </div>
                    <div class="row my-3">
                        <div class="col-md-4">
                            <div class="card bg-danger">
                                <div class="card-header">
                                    <span class=""><i class="product-icon"></i></span> HR SERVICES
                                </div>
                                <div class="card-body">
                                  <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> HR SERVICES PROVIDED BY HR[LIST]</a>
                                  <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Fire to Hire</a>
                                  <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Salary Management</a>
                                  <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Attandance Management</a>
                                </div>
                              </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-danger">
                                <div class="card-header">
                                    <span class=""><i class="product-icon"></i></span> Check IN and Check OUT System 
                                </div>
                                <div class="card-body">
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> User Check </a>
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> User Checkout</a>
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Holiday Management</a>
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> Leave Management</a>
                                </div>
                              </div> 
                        </div>
                        <div class="col-md-4">
                            <div class="card bg-danger">
                                <div class="card-header">
                                    <span class=""><i class="product-icon"></i></span> NEAR BY USER FOUNDATION
                                </div>
                                <div class="card-body">
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> SERVICES NEAR BY USER</a>
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> SEARCH PATTERN FILTER</a>
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> NEAR BY BEST SERVICES PROVIDERS</a>
                                    <a href="#" class=" text-white nav-link"><i class="text-dark fa fa-check "></i> USER FEEDBACK SERVCES PROVIDER</a>
                                </div>
                              </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endblock content %}
    {% include 'deepakblog/footer.html' %}
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/all.min.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
    
</body>
</html>